// Shared, runtime-agnostic pieces of @incy/link-encoder.
//
// Everything in this file is pure JS over strings/Uint8Array — no
// node:crypto, no WebCrypto. The two entry points (`index.ts` for
// Node, `web.ts` for browsers/workers/edge) import from here so the
// wire format is defined exactly once.

import { KEYMAT_A_B64, KEYMAT_B_B64 } from './keymat.js';

// --- Salt parts. These four strings are concatenated in order and
// fed into the SHA-256 KDF. They live as separate constants so that
// — like in the client apps — a single-file grep doesn't reveal the
// full salt at once. Yes, you can see all four right here. Read the
// header comment in index.ts again.

const SALT_P1 = 'incy';
const SALT_P2 = 'deep';
const SALT_P3 = 'crypt1';
const SALT_P4 = 'v2026.06';

// --- Keymat layout. Two opaque 4 KiB blobs are inlined as base64 in
// `keymat.ts` (auto-generated from `assets/incy_assets_a.bin` and
// `assets/incy_assets_b.bin`). The KDF pulls 32 bytes from each at
// fixed offsets. Identical bytes ship inside the iOS/Android/Desktop
// apps so a link generated by this package decodes on every platform
// bit-for-bit.

const KEYMAT_A_OFFSET = 1024;
const KEYMAT_B_OFFSET = 2048;
const KEYMAT_LEN = 32;

export const EXPECTED_KEY_FINGERPRINT =
  'b6bf708471cc90043232967660aade86a50b4e57929db2e53c5fa34db624c08c';

export const SCHEME = 'incy';
export const HOST = 'crypt1';
export const LINK_PREFIX = `${SCHEME}://${HOST}/`;

export const IV_LEN = 12;
export const TAG_LEN = 16;

// --- Byte helpers (no Buffer dependency; Buffer used as a fast path
// when present so the Node entry doesn't pay the atob cost).

declare const Buffer: any;

export function b64Decode(s: string): Uint8Array {
  if (typeof Buffer !== 'undefined') {
    return new Uint8Array(Buffer.from(s, 'base64'));
  }
  const bin = atob(s);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

function b64Encode(bytes: Uint8Array): string {
  if (typeof Buffer !== 'undefined') {
    return Buffer.from(bytes).toString('base64');
  }
  let bin = '';
  const CHUNK = 0x8000;
  for (let i = 0; i < bytes.length; i += CHUNK) {
    bin += String.fromCharCode(...bytes.subarray(i, i + CHUNK));
  }
  return btoa(bin);
}

// --- Base64url helpers (no padding, matches RFC 4648 §5).

export function b64urlEncode(bytes: Uint8Array): string {
  return b64Encode(bytes).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/g, '');
}

export function b64urlDecode(s: string): Uint8Array {
  const padded = s.replace(/-/g, '+').replace(/_/g, '/');
  const pad = padded.length % 4 === 0 ? '' : '='.repeat(4 - (padded.length % 4));
  return b64Decode(padded + pad);
}

export function concatBytes(...parts: Uint8Array[]): Uint8Array {
  let len = 0;
  for (const p of parts) len += p.length;
  const out = new Uint8Array(len);
  let off = 0;
  for (const p of parts) {
    out.set(p, off);
    off += p.length;
  }
  return out;
}

export function bytesToHex(bytes: Uint8Array): string {
  let s = '';
  for (const b of bytes) s += b.toString(16).padStart(2, '0');
  return s;
}

/**
 * The exact byte sequence fed into SHA-256 to derive K1. The caller
 * (Node or Web entry) hashes it with its own runtime's SHA-256 and
 * verifies the result against `EXPECTED_KEY_FINGERPRINT`.
 */
export function keySeed(): Uint8Array {
  const a = b64Decode(KEYMAT_A_B64);
  const b = b64Decode(KEYMAT_B_B64);
  if (a.length < KEYMAT_A_OFFSET + KEYMAT_LEN || b.length < KEYMAT_B_OFFSET + KEYMAT_LEN) {
    throw new Error('incy-link-encoder: keymat assets are smaller than expected');
  }
  const enc = new TextEncoder();
  return concatBytes(
    enc.encode(SALT_P1),
    enc.encode(SALT_P2),
    enc.encode(SALT_P3),
    enc.encode(SALT_P4),
    a.subarray(KEYMAT_A_OFFSET, KEYMAT_A_OFFSET + KEYMAT_LEN),
    b.subarray(KEYMAT_B_OFFSET, KEYMAT_B_OFFSET + KEYMAT_LEN)
  );
}

export function fingerprintMismatchError(got: string): Error {
  return new Error(
    `incy-link-encoder: derived K1 fingerprint mismatch (expected ${EXPECTED_KEY_FINGERPRINT}, got ${got}) — ` +
      `keymat assets are out of sync with the published clients. Reinstall the package or report a bug.`
  );
}

// --- Compact JSON with stable key order. iOS uses
// `JSONSerialization` with `.sortedKeys`; Android/Desktop hand-roll
// the same. We do the same here so the GCM-authenticated bytes are
// byte-for-byte identical on every platform.

function sortedCompactJson(payload: Record<string, unknown>): string {
  const keys = Object.keys(payload).sort();
  const parts = keys.map((k) => `${JSON.stringify(k)}:${JSON.stringify(payload[k])}`);
  return `{${parts.join(',')}}`;
}

/** Optional metadata attached to an encrypted link. */
export interface EncryptOptions {
  /**
   * Human-readable subscription name. The receiving app shows this
   * in the import confirmation sheet (e.g. "MyProvider VPN — Confirm
   * import?"). Truncated to 128 chars by clients.
   */
  name?: string;
}

/** Result of decrypting a `incy://crypt1/...` link. */
export interface DecryptedLink {
  /** The embedded subscription URL. */
  url: string;
  /** Optional human-readable name supplied at encrypt time. */
  name?: string;
}

/** Build the UTF-8 plaintext bytes for a link payload. */
export function buildPlaintext(url: string, opts: EncryptOptions = {}): Uint8Array {
  if (!url || typeof url !== 'string') {
    throw new TypeError('encryptLink: url must be a non-empty string');
  }
  const payload: Record<string, unknown> = { url, v: 1 };
  if (opts.name && opts.name.length > 0) {
    payload.n = opts.name.slice(0, 128);
  }
  return new TextEncoder().encode(sortedCompactJson(payload));
}

/** Assemble the final deep-link string from iv || ct || tag. */
export function assembleLink(wire: Uint8Array): string {
  return `${LINK_PREFIX}${b64urlEncode(wire)}`;
}

/**
 * Validate a deep-link string and split its payload into iv / ct+tag
 * parts. Throws on anything malformed (auth failure is the caller's
 * runtime-specific concern).
 */
export function parseLink(link: string): { iv: Uint8Array; ct: Uint8Array; tag: Uint8Array } {
  if (!link || typeof link !== 'string') {
    throw new TypeError('decryptLink: link must be a non-empty string');
  }
  if (!link.startsWith(LINK_PREFIX)) {
    throw new Error(`decryptLink: expected ${LINK_PREFIX} prefix`);
  }
  const payload = link.slice(LINK_PREFIX.length).replace(/\/+$/g, '');
  if (payload.length === 0) {
    throw new Error('decryptLink: empty payload');
  }
  const wire = b64urlDecode(payload);
  if (wire.length < IV_LEN + TAG_LEN + 1) {
    throw new Error('decryptLink: payload too short');
  }
  return {
    iv: wire.subarray(0, IV_LEN),
    ct: wire.subarray(IV_LEN, wire.length - TAG_LEN),
    tag: wire.subarray(wire.length - TAG_LEN),
  };
}

/** Parse decrypted plaintext bytes into the public result shape. */
export function parsePlaintext(plaintext: Uint8Array): DecryptedLink {
  let parsed: { url?: unknown; n?: unknown; v?: unknown };
  try {
    parsed = JSON.parse(new TextDecoder().decode(plaintext));
  } catch {
    throw new Error('decryptLink: malformed plaintext');
  }
  if (typeof parsed.url !== 'string' || parsed.url.length === 0) {
    throw new Error('decryptLink: missing url field');
  }
  const result: DecryptedLink = { url: parsed.url };
  if (typeof parsed.n === 'string' && parsed.n.length > 0) result.name = parsed.n;
  return result;
}

/**
 * Library version + key fingerprint. Useful when reporting bugs or
 * verifying the client/server are running compatible builds.
 */
export const VERSION = '1.2.0';
export const SCHEME_VERSION = 'crypt1';
export const KEY_FINGERPRINT = EXPECTED_KEY_FINGERPRINT;

/** One deep-link scheme's identifying constants. */
export interface SchemeInfo {
  /** URL host segment, e.g. `crypt1`. */
  host: string;
  /** Full link prefix, e.g. `incy://crypt1/`. */
  prefix: string;
  /** SHA-256 of that scheme's AES key K, for drift detection. */
  keyFingerprint: string;
}

/**
 * Registry of every deep-link scheme this build understands. Today
 * that's only `crypt1`; when the key is rotated a future release adds
 * `crypt2` here (fresh salt + keymat + fingerprint) while keeping
 * `crypt1` so old links in chat histories never stop decoding. Shaped
 * as a keyed record so callers can branch on scheme without a version
 * bump breaking them — cf. cryptohapp's HAPP_CRYPTO_V2/V3/V4 exports.
 */
export const SCHEMES: Readonly<Record<string, SchemeInfo>> = Object.freeze({
  crypt1: Object.freeze({
    host: HOST,
    prefix: LINK_PREFIX,
    keyFingerprint: EXPECTED_KEY_FINGERPRINT,
  }),
});
